### ISSUE TITLE
Errors in graph.hpp

### ISSUE THREAD

**Issue by lazyprop** [nibeditabh/StarPlat#35]
There are compilation errors in `graphcode/graph.hpp`, most likely the consequence of a merge error.

- Re-definition of `addEdge`: [line 240](https://github.com/nibeditabh/StarPlat/blob/8644beac761e5adcc6dc6af1c7d2efaf44d78f02/graphcode/graph.hpp#L240) and [line 295](https://github.com/nibeditabh/StarPlat/blob/8644beac761e5adcc6dc6af1c7d2efaf44d78f02/graphcode/graph.hpp#L295)
- Interleaved definition of `getNeighbors` with `getNeighbors` and `getInNeighbors`: [line 748](https://github.com/nibeditabh/StarPlat/blob/8644beac761e5adcc6dc6af1c7d2efaf44d78f02/graphcode/graph.hpp#L748), [line 753](https://github.com/nibeditabh/StarPlat/blob/8644beac761e5adcc6dc6af1c7d2efaf44d78f02/graphcode/graph.hpp#L753) and [line 796](https://github.com/nibeditabh/StarPlat/blob/8644beac761e5adcc6dc6af1c7d2efaf44d78f02/graphcode/graph.hpp#L796).

Due to this likely being caused by a merge error, there might be more such bugs which I have not found yet. To find them (or confirm that there aren't anymore) it may be better to go through the git log and find the problematic merge. However, for now, I have manually fixed the aforementioned issues in [my fork](https://github.com/lazyprop/StarPlat/tree/WorkingBranch) and I can submit a pull request for the same, should that be the preferred course of action.

**Comment by nibeditabh** [comment]
Fixed the issue.
