### ISSUE TITLE
Error while building compiler

### ISSUE THREAD

**Issue by Fazalcode1** [nibeditabh/StarPlat#38]
While creating the Starplat compiler, I got the below error.

fazal@Shaiks-Air ~ % cd GraphDSL/src
fazal@Shaiks-Air src % make
mkdir -p bin
g++ -std=c++11  -g  -c maincontext/MainContext.cpp -o bin/MainContext.o
g++ -std=c++11  -g  -c ast/ASTHelper.cpp -o bin/ASTHelper.o
g++ -std=c++11  -g  -c symbolutil/SymbolTableBuilder.cpp -o bin/SymbolTableBuilder.o
g++ -std=c++11  -g  -c symbolutil/SymbolTableNew.cpp -o bin/SymbolTableNew.o
/Library/Developer/CommandLineTools/usr/bin/make -C parser
bison -dy lrparser.y
lrparser.y:71.42-52: symbol return_func is used, but is not defined as a token and has no rules
make[1]: *** [parse] Error 1
make: *** [bin/y.tab.o] Error 2

**Comment by lazyprop** [comment]
@Fazalcode1 Which branch are you on? The working branch compiles without problems for me.

**Comment by Fazalcode1** [comment]
> @Fazalcode1 Which branch are you on? The working branch compiles without problems for me. 

Working branch itself

**Comment by lazyprop** [comment]
On my machine, the aforementioned error only occurs as a warning.
```
bison -dy lrparser.y
lrparser.y:71.42-52: warning: symbol ‘return_func’ is used, but is not defined as a token and has no rules [-Wother]
   71 | %type <node> function_def function_data  return_func function_body param
      |                                          ^~~~~~~~~~~
```
and the compilation proceeds without problems.

**Comment by Fazalcode1** [comment]
@nibeditabh can you look into this at the earliest, please?

**Comment by nibeditabh** [comment]
It works fine for me. Can you remove the return_func from line 71 in %type<node> statement? I guess it would work for you then without errors.
